# This is a TOML document
title = "TOML Example"

[owner]
	dob = 1979-05-27T07:32:00-08:00
	name = "Tom Preston-Werner"

[database]
	data = [["delta", "phi"], [3.14]]
	ports = [8000, 8001, 8002]
	enabled = true

	[database.temp_targets]
		cpu = 79.5
		case = 72.0

[servers]

	[servers.alpha]
		role = "frontend"
		ip = "10.0.0.1"

	[servers.beta]
		role = "backend"
		ip = "10.0.0.2"

